In [1]:
import sys
import os
import numpy as np
import pandas as pd

In [3]:
recitation_005 = [
    "N13809508",
    "N18199504",
    "N16001991",
    "N16916324",
    "N18596839",
    "N18526195",
    "N16027400",
    "N11177093",
    "N11310782",
    "N17013875",
    "N13831137",
    "N14911550",
    "N13861867",
    "N11903396",
    "N17205248",
    "N15166474",
    "N19907747",
    "N14316466",
    "N19999440",
    "N13548655",
    "N13403209",
    "N13399342",
    "N19734263",
    "N19926743",
    "N18700219",
    "N13346424",
    "N14990563",
    "N19515548",
    "N16523340"
]

recitation_004 = [
    "N11203880",
    "N18589927",
    "N17346010",
    "N18446148",
    "N10316106",
    "N17136547",
    "N13893886",
    "N16067960",
    "N10537652",
    "N18039993",
    "N17131052",
    "N18460387",
    "N16249918",
    "N15128472",
    "N18784639",
    "N16201641",
    "N17725651",
    "N14248175",
    "N11333143",
    "N13964888",
    "N18009497",
    "N13283694",
    "N13024255",
    "N17763033",
    "N14652424",
    "N10780064",
    "N18392087",
    "N14787877",
    "N17357239",
    "N10948596"
]

In [4]:
all_students = [
    "N18508306",
    "N12350768",
    "N16416773",
    "N11203880",
    "N18589927",
    "N17346010",
    "N10923012",
    "N13809508",
    "N18199504",
    "N18446148",
    "N12779962",
    "N12010038",
    "N16001991",
    "N10316106",
    "N15541103",
    "N16916324",
    "N18596839",
    "N18526195",
    "N16027400",
    "N11177093",
    "N18212491",
    "N17251395",
    "N16751039",
    "N17136547",
    "N17199739",
    "N19800785",
    "N11310782",
    "N14202633",
    "N15017032",
    "N17013875",
    "N17684158",
    "N19751647",
    "N13831137",
    "N13893886",
    "N17327113",
    "N12922861",
    "N16067960",
    "N10537652",
    "N14911550",
    "N18039993",
    "N17380508",
    "N11965140",
    "N13632683",
    "N13861867",
    "N10373951",
    "N17131052",
    "N14962816",
    "N13419835",
    "N11903396",
    "N15166256",
    "N17205248",
    "N15354801",
    "N15166474",
    "N17604339",
    "N19534425",
    "N19907747",
    "N18137068",
    "N14730030",
    "N18339690",
    "N18460387",
    "N14316466",
    "N19999440",
    "N16249918",
    "N15128472",
    "N10539141",
    "N14047038",
    "N13548655",
    "N11288668",
    "N18185842",
    "N13403209",
    "N18784639",
    "N16201641",
    "N13399342",
    "N14741498",
    "N17725651",
    "N14248175",
    "N17474424",
    "N15175721",
    "N17690151",
    "N19734263",
    "N11333143",
    "N11844694",
    "N19926743",
    "N13964888",
    "N12296072",
    "N18009497",
    "N18700219",
    "N13283694",
    "N18022773",
    "N18793063",
    "N18801674",
    "N11925368",
    "N13024255",
    "N17671615",
    "N13346424",
    "N14990563",
    "N17763033",
    "N14652424",
    "N10780064",
    "N14683290",
    "N10662557",
    "N18392087",
    "N13764230",
    "N13182995",
    "N11190290",
    "N19515548",
    "N10647896",
    "N12071272",
    "N14787877",
    "N17357239",
    "N10948596",
    "N10118547",
    "N16523340",
    "N11802024",
    "N16159074",
    "N16301595",
    "N14410933"
]

In [9]:
df = pd.DataFrame(all_students)
df = df.rename(columns={0: 'N_number'})
df['recitation'] = 0

for i, student in enumerate(all_students):
    if student in recitation_005:
        df.loc[i, 'recitation'] = '005'
    elif student in recitation_004:
        df.loc[i, 'recitation'] = '004'
    else:
        df.loc[i, 'recitation'] = 'X'

df.to_csv('all_students.csv', index=False)